/**
 * Contract types for the ssh-files details panel: the inject face the plugin
 * supplies to its registration and the component's composed props. Wire types
 * mirror the host's `lib/types/store.d.ts` shapes so the browser never joins
 * path segments or owns remote paths. Every state/fs call takes the session id
 * first — a panel mounted on conversation A drives only session A's
 * preference and connection, never conversation B's.
 */

import type { PropsLocale, PropsRuntime, TranslateNS } from '@deepseek-ai/dsh-client-ui-slots'

/** The namespace-bound translate seat used by every panel subcomponent. */
export type SshFilesTranslate = TranslateNS<'ssh-files'>

/** The two working modes; each session remembers its own. */
export type SshMode = 'local' | 'ssh'

/** Authentication strategy for one saved server. */
export type SshAuth = 'password' | 'key' | 'agent'

/** One saved server record (host-side wire type). */
export interface SshServer {
  id: string
  name: string
  host: string
  port: number
  username: string
  auth: SshAuth
  password?: string
  keyPath?: string
  root: string
}

/** Server fields the editor form collects (id generated by the host). */
export type SshServerInput = Omit<SshServer, 'id'>

/** The panel's working state for one session. */
export interface SshPanelState {
  /** This session's working mode. */
  mode: SshMode
  /** This session's remembered server id. */
  serverId: string | null
  /** The shared saved-server pool. */
  servers: SshServer[]
  /** Whether this session has a live connection right now. */
  connected: boolean
}

/** The wire response of every state-changing call. */
export interface SshStateResponse {
  state: SshPanelState
  /** The file tree's base when a server is connected; null otherwise. */
  root: string | null
}

/** One file or directory row (host-side wire type, browser-safe mirror). */
export interface SshFileEntry {
  name: string
  path: string
  kind: 'dir' | 'file'
  hidden: boolean
}

/** One listed directory level. */
export interface SshListing {
  path: string
  entries: SshFileEntry[]
}

/** The character-cell size of the panel's terminal. */
export interface SshTerminalSize {
  cols: number
  rows: number
}

/** One frame of the terminal stream (NDJSON line from the host). */
export type SshTerminalFrame =
  /** Replay buffer at attach time: reset the screen, then write it. */
  | { kind: 'snapshot'; data: string; trimmed: boolean }
  /** Live terminal output. */
  | { kind: 'data'; data: string }
  /** The remote shell ended. */
  | { kind: 'exit'; code: number | null; signal: string | null }
  /** The channel failed outside a normal close. */
  | { kind: 'error'; message: string }
  /** Keep-alive. */
  | { kind: 'ping' }

/** The sidebar-tab inject face: all RPC calls this plugin's host route serves. */
export interface SshFilesInjected {
  /** Read the panel state of one session (mode, servers, connection). */
  getState: (sessionId: string, signal?: AbortSignal) => Promise<SshStateResponse>
  /** Switch one session's working mode (also remembered as the default). */
  setMode: (sessionId: string, mode: SshMode) => Promise<SshStateResponse>
  /** Add a server record (shared pool). */
  addServer: (sessionId: string, input: SshServerInput) => Promise<SshStateResponse>
  /** Replace one server record's fields. */
  updateServer: (sessionId: string, id: string, input: SshServerInput) => Promise<SshStateResponse>
  /** Remove one server record (drops connections and prefs that target it). */
  removeServer: (sessionId: string, id: string) => Promise<SshStateResponse>
  /** Connect one session to a saved server; returns fresh state and tree root. */
  connect: (sessionId: string, id: string, signal?: AbortSignal) => Promise<SshStateResponse>
  /** Tear down one session's live connection. */
  disconnect: (sessionId: string) => Promise<SshStateResponse>
  /** List one directory level on a session's active filesystem. */
  list: (sessionId: string, path: string, signal?: AbortSignal) => Promise<SshListing>
  /** Read one text file on a session's active filesystem. */
  read: (sessionId: string, path: string, signal?: AbortSignal) => Promise<string>
  /** Write one text file on a session's active filesystem (created when missing). */
  write: (sessionId: string, path: string, content: string) => Promise<void>
  /** Create one directory on a session's active filesystem. */
  mkdir: (sessionId: string, path: string) => Promise<void>
  /** Delete one file or empty directory on a session's active filesystem. */
  unlink: (sessionId: string, path: string) => Promise<void>
  /** Open one session on this server: new conversation defaulting to it. */
  openNewSessionOn: (serverId: string) => Promise<void>
  /** Open a local path with the operating system's default application. */
  openLocalDefault: (path: string) => Promise<void>
  /** Open a local path in VS Code (the configured `code` executable). */
  openLocalCode: (path: string) => Promise<void>
  /** Open a local path in MarkText (the configured `marktext` executable). */
  openLocalMarktext: (path: string) => Promise<void>
  /**
   * The session's terminal output stream URL, carrying the attaching size.
   * Attaching is what opens the remote shell.
   */
  terminalStreamUrl: (sessionId: string, size: SshTerminalSize) => string
  /** Send keystrokes to the session's remote shell. */
  writeTerminal: (sessionId: string, data: string) => Promise<void>
  /** Report this client's terminal size to the session's remote PTY. */
  resizeTerminal: (sessionId: string, size: SshTerminalSize) => Promise<void>
  /** End the session's remote shell; the next attach starts a fresh one. */
  closeTerminal: (sessionId: string) => Promise<void>
}

/** Composed props of the ssh-files sidebar tab body. */
export type SshFilesPanelProps =
  & PropsRuntime<'sidebar.right.pane.tab'>
  & PropsLocale<'ssh-files'>
  & SshFilesInjected
